BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET search_path = public, extensions;
SELECT plan(24);
INSERT INTO public.workspaces(id) VALUES ('durable-intake');
INSERT INTO private.intake_sources(workspace_id,secret_hash,enabled) VALUES ('durable-intake',repeat('e',64),true);
CREATE TEMP TABLE fixture AS SELECT jsonb_build_object('name','Synthetic','email','repeat@example.test',
  'company','Synthetic','message',E'  Exact\noriginal "message"  ') AS payload;
SELECT is(has_function_privilege('anon','public.stage_source_inquiry(text,text,jsonb)','EXECUTE'),false,'browser cannot stage directly');
SELECT is(has_function_privilege('authenticated','public.claim_intake_delivery()','EXECUTE'),false,'browser cannot claim');
SELECT is(has_function_privilege('authenticated','public.retry_intake_delivery(uuid)','EXECUTE'),false,'browser cannot recover operator jobs');
SELECT is(has_table_privilege('authenticated','private.intake_deliveries','SELECT'),false,'private transport data hidden');
SELECT lives_ok('SELECT public.stage_source_inquiry(repeat(''e'',64),''durable-one'',(SELECT payload FROM fixture))','website queues durably');
SELECT is((public.stage_source_inquiry(repeat('e',64),'durable-one',(SELECT payload FROM fixture))->>'duplicate')::boolean,true,'website retry reuses delivery');
SELECT is((SELECT count(*) FROM private.intake_deliveries WHERE workspace_id = 'durable-intake'),1::bigint,'one durable delivery');
SELECT throws_ok('SELECT public.stage_source_inquiry(repeat(''e'',64),''durable-one'',(SELECT payload || ''{"message":"Changed"}'' FROM fixture))','P0409',NULL,'changed retry conflicts');
SELECT is((SELECT count(*) FROM public.inquiries WHERE workspace_id = 'durable-intake'),0::bigint,'queued acknowledgement is not canonical storage');
CREATE TEMP TABLE packet AS SELECT public.claim_intake_delivery() AS payload;
SELECT is((SELECT payload->>'status' FROM packet),'claimed','Make obtains lease');
SELECT throws_ok('SELECT public.complete_intake_delivery((SELECT (payload->>''deliveryId'')::uuid FROM packet),gen_random_uuid())','P0409',NULL,'wrong lease cannot store');
UPDATE private.intake_deliveries SET lease_until = now() - interval '1 second' WHERE workspace_id = 'durable-intake';
SELECT throws_ok('SELECT public.complete_intake_delivery((SELECT (payload->>''deliveryId'')::uuid FROM packet),(SELECT (payload->>''leaseToken'')::uuid FROM packet))','P0409',NULL,'expired lease cannot store');
CREATE TEMP TABLE stale AS SELECT payload FROM packet;
UPDATE packet SET payload = public.claim_intake_delivery();
SELECT isnt((SELECT payload->>'leaseToken' FROM packet),(SELECT payload->>'leaseToken' FROM stale),'reclaim fences old token');
SELECT throws_ok('SELECT public.complete_intake_delivery((SELECT (payload->>''deliveryId'')::uuid FROM stale),(SELECT (payload->>''leaseToken'')::uuid FROM stale))','P0409',NULL,'stale callback denied');
SELECT is(public.complete_intake_delivery((SELECT (payload->>'deliveryId')::uuid FROM packet),(SELECT (payload->>'leaseToken')::uuid FROM packet))->>'status','stored','completion atomically stores canonical inquiry');
SELECT is((public.complete_intake_delivery((SELECT (payload->>'deliveryId')::uuid FROM packet),(SELECT (payload->>'leaseToken')::uuid FROM packet))->>'duplicate')::boolean,true,'callback retry acknowledges original receipt');
SELECT is((SELECT count(*) FROM public.inquiries WHERE workspace_id = 'durable-intake'),1::bigint,'callback replay stores once');
SELECT is((SELECT original_message FROM public.inquiries WHERE workspace_id = 'durable-intake'),(SELECT payload->>'message' FROM fixture),'original exact text preserved');
SELECT is((SELECT payload ? 'message' OR payload ? 'inquiry' FROM packet),false,'Make sees only opaque route data');
SELECT public.stage_source_inquiry(repeat('e',64),'durable-two',(SELECT payload FROM fixture));
UPDATE packet SET payload = public.claim_intake_delivery();
UPDATE private.intake_deliveries SET attempts = 8, lease_until = now() - interval '1 second' WHERE state = 'processing' AND workspace_id = 'durable-intake';
SELECT is(public.claim_intake_delivery(),NULL::jsonb,'exhausted delivery no longer auto claims');
SELECT is((SELECT state FROM private.intake_deliveries WHERE source_inquiry_id = 'durable-two'),'failed','failure remains observable');
SELECT is(public.retry_intake_delivery((SELECT (payload->>'deliveryId')::uuid FROM packet)),true,'operator can recover same original');
SELECT is(public.claim_intake_delivery()->>'status','claimed','recovered delivery is claimable');
UPDATE private.intake_router_gate SET request_count = 120;
SELECT throws_ok('SELECT public.claim_intake_delivery()','P0429',NULL,'router limit enforced');
SELECT * FROM finish();
ROLLBACK;
