BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET search_path = public, extensions;
SELECT plan(24);
INSERT INTO auth.users(id, email_confirmed_at) VALUES ('00000000-0000-4000-8000-000000000021', now());
INSERT INTO public.workspaces(id) VALUES ('queue-a'), ('queue-b');
INSERT INTO public.identity_bindings(auth_user_id, workspace_id) VALUES ('00000000-0000-4000-8000-000000000021', 'queue-a');
INSERT INTO public.subscriptions(workspace_id) VALUES ('queue-a');
INSERT INTO public.inquiries(workspace_id, id, original_message) VALUES
  ('queue-a', 'first', 'Immutable original'), ('queue-a', 'second', 'Second original'), ('queue-b', 'foreign', 'Foreign original');
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub', '00000000-0000-4000-8000-000000000021', true);
SELECT throws_ok('SELECT public.enqueue_own_analysis(''first'')', 'P0503', NULL, 'disabled workers reject queue creation');
RESET ROLE;
UPDATE private.processing_configuration SET enabled = true;
SELECT public.processing_worker_heartbeat('00000000-0000-4000-8000-000000000031', true);
SET LOCAL ROLE authenticated;
SELECT throws_ok('SELECT public.enqueue_own_analysis(''foreign'')', 'P0002', NULL, 'foreign inquiries cannot be queued');
SELECT lives_ok('SELECT public.enqueue_own_analysis(''first'', ''request-one'')', 'owned inquiry queues');
SELECT is((SELECT reserved FROM public.usage_periods), 1::bigint, 'credit reserved atomically');
SELECT is((public.enqueue_own_analysis('first', 'request-one')->>'duplicate')::boolean, true, 'same input and request key deduplicated');
SELECT is((SELECT count(*) FROM public.jobs), 1::bigint, 'replay creates no extra job');
SELECT throws_ok('SELECT public.enqueue_own_analysis(''second'', ''request-one'')', 'P0409', NULL, 'changed input conflicts');
SELECT throws_ok('SELECT public.enqueue_own_analysis(''second'', ''request-two'')', 'P0429', NULL, 'plan concurrency enforced');
SELECT is(has_function_privilege('authenticated', 'public.claim_processing_job()', 'EXECUTE'), false, 'browser cannot claim jobs');
SELECT is(has_function_privilege('authenticated', 'public.finish_processing_job(text,text,uuid,jsonb)', 'EXECUTE'), false, 'browser cannot settle usage');
RESET ROLE;
CREATE TEMP TABLE claim AS SELECT public.claim_processing_job() AS payload;
SELECT is(public.claim_processing_job(), NULL::jsonb, 'leased work cannot be claimed twice');
SELECT is(public.finish_processing_job('queue-a', (SELECT payload->>'id' FROM claim), gen_random_uuid(), '{"summary":"Synthetic result"}'), false, 'wrong lease is fenced');
UPDATE public.jobs SET lease_until = now() - interval '1 second' WHERE workspace_id = 'queue-a';
SELECT is(public.finish_processing_job('queue-a', (SELECT payload->>'id' FROM claim), (SELECT (payload->>'leaseToken')::uuid FROM claim), '{"summary":"Synthetic result"}'), false, 'expired lease cannot commit');
UPDATE claim SET payload = public.claim_processing_job();
SELECT is((SELECT (payload->>'attempt')::integer FROM claim), 2, 'crashed work is reclaimed');
SELECT throws_ok('SELECT public.finish_processing_job(''queue-a'', (SELECT payload->>''id'' FROM claim), (SELECT (payload->>''leaseToken'')::uuid FROM claim), ''{"fit_score":101}'')', '22023', NULL, 'database rejects scores above 100');
SELECT throws_ok('SELECT public.finish_processing_job(''queue-a'', (SELECT payload->>''id'' FROM claim), (SELECT (payload->>''leaseToken'')::uuid FROM claim), ''{"fit_score":-1}'')', '22023', NULL, 'database rejects negative scores');
SELECT is(public.finish_processing_job('queue-a', (SELECT payload->>'id' FROM claim), (SELECT (payload->>'leaseToken')::uuid FROM claim), '{"summary":"Synthetic result","fit_score":25}'), true, 'result and accounting commit');
SELECT is((SELECT original_message FROM public.inquiries WHERE workspace_id = 'queue-a' AND id = 'first'), 'Immutable original', 'processing preserves original');
SELECT is((SELECT used FROM public.usage_periods WHERE workspace_id = 'queue-a'), 1::bigint, 'one successful credit charged');
SELECT is(public.finish_processing_job('queue-a', (SELECT payload->>'id' FROM claim), (SELECT (payload->>'leaseToken')::uuid FROM claim), '{"summary":"Synthetic result"}'), false, 'settlement replay cannot charge twice');
SET LOCAL ROLE authenticated;
SELECT public.enqueue_own_analysis('second', 'request-three');
RESET ROLE;
UPDATE claim SET payload = public.claim_processing_job();
SELECT is(public.finish_processing_job('queue-a', (SELECT payload->>'id' FROM claim), (SELECT (payload->>'leaseToken')::uuid FROM claim), NULL), true, 'failed job releases reservation');
SELECT is((SELECT reserved + active_jobs FROM public.usage_periods WHERE workspace_id = 'queue-a'), 0::bigint, 'failure leaves no reserved credits or occupied slots');
SET LOCAL ROLE authenticated;
SELECT public.enqueue_own_analysis('first', 'request-four');
RESET ROLE;
SELECT is((SELECT length(payload_hash) FROM public.jobs WHERE workspace_id = 'queue-a' AND idempotency_key = 'request-four'), 64, 'input integrity uses SHA-256');
UPDATE public.subscriptions SET plan = 'starter', status = 'active', period_start = now() - interval '1 second' WHERE workspace_id = 'queue-a';
SET LOCAL ROLE authenticated;
SELECT throws_ok('SELECT public.enqueue_own_analysis(''second'', ''request-five'')', 'P0429', NULL, 'a period rollover does not create an extra processing slot');
SELECT * FROM finish();
ROLLBACK;
