BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET search_path = public, extensions;
SELECT plan(8);
UPDATE private.processing_configuration SET enabled = true;
UPDATE private.processing_workers SET ready = false;
SELECT is(public.processing_available(), false, 'operator flag alone cannot enable processing');
SELECT public.processing_worker_heartbeat('00000000-0000-4000-8000-000000000051', true);
SELECT is(public.processing_available(), true, 'fresh worker and operator flag enable processing');
UPDATE private.processing_workers SET last_seen = now() - interval '61 seconds';
SELECT is(public.processing_available(), false, 'dead worker automatically blocks new processing');
SELECT public.processing_worker_heartbeat('00000000-0000-4000-8000-000000000051', true);
SELECT public.processing_worker_heartbeat('00000000-0000-4000-8000-000000000051', false);
SELECT is(public.processing_available(), false, 'graceful shutdown blocks new processing');
SELECT public.processing_worker_heartbeat('00000000-0000-4000-8000-000000000051', true);
UPDATE private.processing_configuration SET enabled = false;
SELECT is(public.processing_available(), false, 'healthy worker never overrides operator pause');
SELECT is(has_function_privilege('authenticated', 'public.processing_worker_heartbeat(uuid,boolean)', 'EXECUTE'), false, 'browser cannot fabricate a heartbeat');
SELECT is(has_function_privilege('anon', 'public.processing_readiness()', 'EXECUTE'), false, 'readiness is not anonymous');
SELECT is((public.processing_readiness()->>'enabled')::boolean, false, 'readiness reports actual operator state');
SELECT * FROM finish();
ROLLBACK;
