import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

const EFFECTIVE_DATE = '11 August 2026';
const CONTACT_EMAIL = 'nodalxai@gmail.com';
const COMPANY = 'NODALxAI';

export default function Terms() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-white dark:bg-neutral-950 text-neutral-900 dark:text-neutral-100">
      <div className="max-w-2xl mx-auto px-6 py-16">
        <button
          onClick={() => navigate('/')}
          className="inline-flex items-center gap-2 text-sm text-neutral-500 hover:text-neutral-900 dark:hover:text-white transition-colors mb-10"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to home
        </button>

        <h1 className="text-3xl font-bold text-neutral-900 dark:text-white mb-2">Terms of Service</h1>
        <p className="text-sm text-neutral-500 dark:text-neutral-400 mb-10">Effective date: {EFFECTIVE_DATE}</p>

        <div className="space-y-8 text-sm leading-relaxed text-neutral-700 dark:text-neutral-300">

          <section>
            <h2 className="text-base font-semibold text-neutral-900 dark:text-white mb-3">1. Acceptance</h2>
            <p>By creating an account or using {COMPANY}, you agree to these Terms of Service. If you do not agree, do not use the service.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 dark:text-white mb-3">2. Description of service</h2>
            <p>{COMPANY} is a B2B SaaS platform that helps businesses capture, qualify, and respond to inbound inquiries automatically using AI. The service is provided as-is during the early access period.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 dark:text-white mb-3">3. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Use the service for spam, unsolicited messaging, or deceptive communications.</li>
              <li>Submit or process personal data of individuals without a lawful basis to do so.</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the platform or its APIs.</li>
              <li>Use the service for any activity that violates applicable law.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 dark:text-white mb-3">4. Your data</h2>
            <p>You retain ownership of all data you input into {COMPANY}. By using the service, you grant us a limited licence to process that data solely to provide the service to you, as described in our Privacy Policy.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 dark:text-white mb-3">5. AI-generated content</h2>
            <p>Reply drafts and lead scores generated by {COMPANY} are suggestions only. You are responsible for reviewing and approving any AI-generated content before it is sent to your customers. We do not guarantee the accuracy or suitability of AI outputs.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 dark:text-white mb-3">6. Service availability</h2>
            <p>During the early access period, the service is provided without uptime guarantees. We will endeavour to keep downtime minimal but cannot be held liable for service interruptions.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 dark:text-white mb-3">7. Limitation of liability</h2>
            <p>To the maximum extent permitted by applicable law, {COMPANY} and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service, including but not limited to lost revenue, lost data, or business interruption.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 dark:text-white mb-3">8. Termination</h2>
            <p>You may stop using the service at any time. We reserve the right to suspend or terminate accounts that violate these terms. Upon termination, you may request deletion of your data as described in our Privacy Policy.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 dark:text-white mb-3">9. Governing law</h2>
            <p>These terms are governed by the laws of India. Any disputes shall be subject to the jurisdiction of courts in India.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 dark:text-white mb-3">10. Changes to these terms</h2>
            <p>We may update these terms from time to time. We will notify users of material changes by email or via the dashboard. Continued use after notification constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 dark:text-white mb-3">11. Contact</h2>
            <p>For any questions about these terms: <a href={`mailto:${CONTACT_EMAIL}`} className="text-black dark:text-white dark:text-neutral-400 hover:underline">{CONTACT_EMAIL}</a></p>
          </section>
        </div>
      </div>
    </div>
  );
}
